export enum ResponseStatus {
    SUCCESS = 1,
    VALIDATION_ERROR = 10,
    INVALID = 11,
    EXCEPTION = 12,
    NOTDELETED = 13,
    NOTCREATED = 14,
    NOTUPDATED = 15,
    MULTIINSERTDELETE = 16,
    USERNOTEXIST = 17,
    RECORDNOTEXIST = 18,
    INVALIDCAPTCHA = 19,
    UNMAPPEDSUCCESS = 20,
    USERNAME_PASSWORD_NOTMATCHED_CODE = 20
}